// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { defineConfig } from "prisma/config";
import dotenv from "dotenv";
import path from "path";

// Asegura que Prisma cargue las variables desde la .env en la RAÍZ del monorepo
// (el comando se ejecuta dentro de apps/api, por lo que dotenv por defecto no la encuentra)
const rootEnvPath = path.resolve(__dirname, "..", "..", ".env");
dotenv.config({ path: rootEnvPath });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
